"""Customer portal services compatibility module.

Re-exports customer portal helpers from focused submodules.
"""

import logging

from app.services.customer_portal_context import (
    _format_address,
    get_allowed_account_ids,
    get_available_portal_offers,
    get_customer_appointments,
    get_dashboard_context,
    get_invoice_billing_contact,
    get_outstanding_balance,
    resolve_customer_account,
)
from app.services.customer_portal_flows import (
    _compute_total_pages,
    _get_offer_recurring_price,
    _resolve_next_billing_date,
    _resolve_payment_provider,
    apply_instant_plan_change,
    cancel_customer_arrangement,
    complete_invoice_payment_intent,
    create_invoice_payment_intent,
    create_topup_intent,
    direct_bank_transfer_enabled,
    direct_bank_transfer_settings,
    get_arrangement_error_context,
    get_billing_page,
    get_change_plan_error_context,
    get_change_plan_page,
    get_change_requests_page,
    get_direct_transfer_topup_page,
    get_installation_detail,
    get_invoice_detail,
    get_new_arrangement_page,
    get_payment_arrangement_detail,
    get_payment_arrangements_page,
    get_payment_methods_page,
    get_payment_page,
    get_plan_change_quote,
    get_service_detail,
    get_service_order_detail,
    get_service_orders_page,
    get_services_page,
    get_topup_page,
    get_usage_history,
    get_usage_page,
    request_plan_migration,
    submit_change_plan,
    submit_direct_transfer_topup,
    submit_payment_arrangement,
    verify_and_record_payment,
    verify_and_record_topup,
)
from app.services.customer_portal_notifications import get_notifications_page
from app.services.customer_portal_session import (
    _CUSTOMER_SESSION_PREFIX,
    _CUSTOMER_SESSIONS,
    _DEFAULT_REMEMBER_TTL,
    _DEFAULT_SESSION_TTL,
    SESSION_COOKIE_NAME,
    _build_current_user,
    _parse_setting_int,
    _session_ttl_seconds,
    create_customer_session,
    get_current_customer,
    get_customer_session,
    get_remember_max_age,
    get_session_max_age,
    invalidate_customer_session,
    list_customer_sessions_for_subscriber,
    refresh_customer_session,
    revoke_customer_sessions_for_subscriber,
    revoke_other_customer_sessions_for_subscriber,
)

logger = logging.getLogger(__name__)

__all__ = [
    "SESSION_COOKIE_NAME",
    "_DEFAULT_SESSION_TTL",
    "_DEFAULT_REMEMBER_TTL",
    "_CUSTOMER_SESSIONS",
    "_CUSTOMER_SESSION_PREFIX",
    "_parse_setting_int",
    "create_customer_session",
    "get_customer_session",
    "refresh_customer_session",
    "invalidate_customer_session",
    "get_current_customer",
    "list_customer_sessions_for_subscriber",
    "revoke_customer_sessions_for_subscriber",
    "revoke_other_customer_sessions_for_subscriber",
    "_session_ttl_seconds",
    "get_session_max_age",
    "get_remember_max_age",
    "_build_current_user",
    "_format_address",
    "get_dashboard_context",
    "resolve_customer_account",
    "get_allowed_account_ids",
    "get_invoice_billing_contact",
    "get_customer_appointments",
    "get_available_portal_offers",
    "get_outstanding_balance",
    "_compute_total_pages",
    "_resolve_next_billing_date",
    "get_billing_page",
    "get_usage_page",
    "get_usage_history",
    "get_services_page",
    "get_service_detail",
    "get_service_orders_page",
    "get_service_order_detail",
    "get_installation_detail",
    "get_change_plan_page",
    "get_plan_change_quote",
    "submit_change_plan",
    "get_change_plan_error_context",
    "get_change_requests_page",
    "get_payment_arrangements_page",
    "get_new_arrangement_page",
    "submit_payment_arrangement",
    "get_arrangement_error_context",
    "cancel_customer_arrangement",
    "get_payment_arrangement_detail",
    "get_invoice_detail",
    "get_notifications_page",
    "_resolve_payment_provider",
    "complete_invoice_payment_intent",
    "create_invoice_payment_intent",
    "create_topup_intent",
    "direct_bank_transfer_enabled",
    "direct_bank_transfer_settings",
    "get_direct_transfer_topup_page",
    "get_payment_methods_page",
    "get_payment_page",
    "get_topup_page",
    "submit_direct_transfer_topup",
    "verify_and_record_payment",
    "verify_and_record_topup",
    "_get_offer_recurring_price",
    "apply_instant_plan_change",
    "request_plan_migration",
]
