"""Service helpers for admin core-network device web routes.

Compatibility module that re-exports helpers from focused submodules.
"""

from app.services.web_network_core_devices_forms import (
    CoreDeviceSubmitResult,
    _form_str,
    build_form_context,
    build_ping_command,
    create_device,
    detail_page_data,
    get_device,
    integrity_error_message,
    list_page_data,
    parse_form_values,
    parent_devices_for_forms,
    pop_sites_for_forms,
    resolve_device_redirect,
    run_ping_probe,
    run_snmp_probe,
    snapshot_for_form,
    update_device,
    validate_values,
)
from app.services.web_network_core_devices_inventory import (
    _device_matches_search,
    collect_devices,
    compute_device_stats,
    devices_filter_data,
    devices_list_page_data,
    devices_search_data,
    filter_devices,
    get_cpe_ports,
    olts_list_page_data,
)
from app.services.web_network_core_devices_views import (
    OFFLINE_REASON_DISPLAY,
    ONLINE_STATUS_CLASSES,
    SIGNAL_QUALITY_CLASSES,
    _classify_ont_signal,
    _get_olt_health,
    backup_overview_page_data,
    _subscriber_display_name,
    consolidated_page_data,
    get_change_request_asset,
    olt_detail_page_data,
    ont_detail_page_data,
    onts_list_page_data,
)

__all__ = [
    "CoreDeviceSubmitResult",
    "_form_str",
    "build_form_context",
    "build_ping_command",
    "create_device",
    "detail_page_data",
    "get_device",
    "integrity_error_message",
    "list_page_data",
    "parse_form_values",
    "parent_devices_for_forms",
    "pop_sites_for_forms",
    "resolve_device_redirect",
    "run_ping_probe",
    "run_snmp_probe",
    "snapshot_for_form",
    "update_device",
    "validate_values",
    "_device_matches_search",
    "collect_devices",
    "compute_device_stats",
    "devices_filter_data",
    "devices_list_page_data",
    "devices_search_data",
    "filter_devices",
    "get_cpe_ports",
    "olts_list_page_data",
    "OFFLINE_REASON_DISPLAY",
    "ONLINE_STATUS_CLASSES",
    "SIGNAL_QUALITY_CLASSES",
    "_classify_ont_signal",
    "_get_olt_health",
    "backup_overview_page_data",
    "_subscriber_display_name",
    "consolidated_page_data",
    "get_change_request_asset",
    "olt_detail_page_data",
    "ont_detail_page_data",
    "onts_list_page_data",
]
