"""enhance_nas_device_and_add_provisioning

Revision ID: c106b739a7ee
Revises: c39ea6fb3c1e
Create Date: 2026-01-14 05:51:59.370310

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c106b739a7ee'
down_revision = 'c39ea6fb3c1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # First, add new values to the existing nasvendor enum
    op.execute("ALTER TYPE nasvendor ADD VALUE IF NOT EXISTS 'huawei'")
    op.execute("ALTER TYPE nasvendor ADD VALUE IF NOT EXISTS 'ubiquiti'")
    op.execute("ALTER TYPE nasvendor ADD VALUE IF NOT EXISTS 'juniper'")
    op.execute("ALTER TYPE nasvendor ADD VALUE IF NOT EXISTS 'cambium'")
    op.execute("ALTER TYPE nasvendor ADD VALUE IF NOT EXISTS 'nokia'")
    op.execute("ALTER TYPE nasvendor ADD VALUE IF NOT EXISTS 'zte'")

    # Create new enum types
    connectiontype = postgresql.ENUM('pppoe', 'dhcp', 'ipoe', 'static', 'hotspot', name='connectiontype', create_type=False)
    connectiontype.create(op.get_bind(), checkfirst=True)

    provisioningaction = postgresql.ENUM('create_user', 'delete_user', 'suspend_user', 'unsuspend_user', 'change_speed', 'change_ip', 'reset_session', 'get_user_info', 'backup_config', 'restore_config', name='provisioningaction', create_type=False)
    provisioningaction.create(op.get_bind(), checkfirst=True)

    configbackupmethod = postgresql.ENUM('ssh', 'api', 'tftp', 'ftp', 'snmp', name='configbackupmethod', create_type=False)
    configbackupmethod.create(op.get_bind(), checkfirst=True)

    nasdevicestatus = postgresql.ENUM('active', 'maintenance', 'offline', 'decommissioned', name='nasdevicestatus', create_type=False)
    nasdevicestatus.create(op.get_bind(), checkfirst=True)

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'provisioning_templates' not in existing_tables:
        op.create_table('provisioning_templates',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=160), nullable=False),
        sa.Column('code', sa.String(length=80), nullable=True),
        sa.Column('vendor', postgresql.ENUM('mikrotik', 'huawei', 'ubiquiti', 'cisco', 'juniper', 'cambium', 'nokia', 'zte', 'other', name='nasvendor', create_type=False), nullable=False),
        sa.Column('connection_type', postgresql.ENUM('pppoe', 'dhcp', 'ipoe', 'static', 'hotspot', name='connectiontype', create_type=False), nullable=False),
        sa.Column('action', postgresql.ENUM('create_user', 'delete_user', 'suspend_user', 'unsuspend_user', 'change_speed', 'change_ip', 'reset_session', 'get_user_info', 'backup_config', 'restore_config', name='provisioningaction', create_type=False), nullable=False),
        sa.Column('template_content', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('placeholders', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('execution_method', sa.String(length=40), nullable=True),
        sa.Column('expected_output', sa.Text(), nullable=True),
        sa.Column('timeout_seconds', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_default', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
        )
    if 'nas_config_backups' not in existing_tables:
        op.create_table('nas_config_backups',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('nas_device_id', sa.UUID(), nullable=False),
        sa.Column('config_content', sa.Text(), nullable=False),
        sa.Column('config_hash', sa.String(length=64), nullable=True),
        sa.Column('config_format', sa.String(length=40), nullable=True),
        sa.Column('config_size_bytes', sa.Integer(), nullable=True),
        sa.Column('backup_method', postgresql.ENUM('ssh', 'api', 'tftp', 'ftp', 'snmp', name='configbackupmethod', create_type=False), nullable=True),
        sa.Column('is_scheduled', sa.Boolean(), nullable=False),
        sa.Column('is_manual', sa.Boolean(), nullable=False),
        sa.Column('has_changes', sa.Boolean(), nullable=False),
        sa.Column('changes_summary', sa.Text(), nullable=True),
        sa.Column('is_current', sa.Boolean(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_by', sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(['nas_device_id'], ['nas_devices.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if 'provisioning_logs' not in existing_tables:
        op.create_table('provisioning_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('nas_device_id', sa.UUID(), nullable=True),
        sa.Column('subscriber_id', sa.UUID(), nullable=True),
        sa.Column('template_id', sa.UUID(), nullable=True),
        sa.Column('action', postgresql.ENUM('create_user', 'delete_user', 'suspend_user', 'unsuspend_user', 'change_speed', 'change_ip', 'reset_session', 'get_user_info', 'backup_config', 'restore_config', name='provisioningaction', create_type=False), nullable=False),
        sa.Column('command_sent', sa.Text(), nullable=True),
        sa.Column('response_received', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=40), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('execution_time_ms', sa.Integer(), nullable=True),
        sa.Column('triggered_by', sa.String(length=120), nullable=True),
        sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['nas_device_id'], ['nas_devices.id'], ),
        sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
        sa.ForeignKeyConstraint(['template_id'], ['provisioning_templates.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    nas_columns = {col["name"] for col in inspector.get_columns("nas_devices")}
    def _add_nas_col(name, column):
        nonlocal nas_columns
        if name not in nas_columns:
            op.add_column('nas_devices', column)
            nas_columns.add(name)

    _add_nas_col('code', sa.Column('code', sa.String(length=60), nullable=True))
    _add_nas_col('model', sa.Column('model', sa.String(length=120), nullable=True))
    _add_nas_col('serial_number', sa.Column('serial_number', sa.String(length=120), nullable=True))
    _add_nas_col('firmware_version', sa.Column('firmware_version', sa.String(length=80), nullable=True))
    _add_nas_col('pop_site_id', sa.Column('pop_site_id', sa.UUID(), nullable=True))
    _add_nas_col('rack_position', sa.Column('rack_position', sa.String(length=40), nullable=True))
    _add_nas_col('management_ip', sa.Column('management_ip', sa.String(length=64), nullable=True))
    _add_nas_col('management_port', sa.Column('management_port', sa.Integer(), nullable=True))
    _add_nas_col('nas_ip', sa.Column('nas_ip', sa.String(length=64), nullable=True))
    _add_nas_col('coa_port', sa.Column('coa_port', sa.Integer(), nullable=True))
    _add_nas_col('ssh_username', sa.Column('ssh_username', sa.String(length=120), nullable=True))
    _add_nas_col('ssh_password', sa.Column('ssh_password', sa.String(length=255), nullable=True))
    _add_nas_col('ssh_key', sa.Column('ssh_key', sa.Text(), nullable=True))
    _add_nas_col('api_username', sa.Column('api_username', sa.String(length=120), nullable=True))
    _add_nas_col('api_password', sa.Column('api_password', sa.String(length=255), nullable=True))
    _add_nas_col('api_token', sa.Column('api_token', sa.Text(), nullable=True))
    _add_nas_col('api_url', sa.Column('api_url', sa.String(length=500), nullable=True))
    _add_nas_col('snmp_community', sa.Column('snmp_community', sa.String(length=120), nullable=True))
    _add_nas_col('snmp_version', sa.Column('snmp_version', sa.String(length=10), nullable=True))
    _add_nas_col('snmp_port', sa.Column('snmp_port', sa.Integer(), nullable=True))
    _add_nas_col('supported_connection_types', sa.Column('supported_connection_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    _add_nas_col('default_connection_type', sa.Column('default_connection_type', postgresql.ENUM('pppoe', 'dhcp', 'ipoe', 'static', 'hotspot', name='connectiontype', create_type=False), nullable=True))
    _add_nas_col('backup_enabled', sa.Column('backup_enabled', sa.Boolean(), server_default='false', nullable=False))
    _add_nas_col('backup_method', sa.Column('backup_method', postgresql.ENUM('ssh', 'api', 'tftp', 'ftp', 'snmp', name='configbackupmethod', create_type=False), nullable=True))
    _add_nas_col('backup_schedule', sa.Column('backup_schedule', sa.String(length=60), nullable=True))
    _add_nas_col('last_backup_at', sa.Column('last_backup_at', sa.DateTime(timezone=True), nullable=True))
    _add_nas_col('status', sa.Column('status', postgresql.ENUM('active', 'maintenance', 'offline', 'decommissioned', name='nasdevicestatus', create_type=False), server_default='active', nullable=False))
    _add_nas_col('last_seen_at', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    _add_nas_col('notes', sa.Column('notes', sa.Text(), nullable=True))
    _add_nas_col('tags', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    _add_nas_col('network_device_id', sa.Column('network_device_id', sa.UUID(), nullable=True))
    op.alter_column('nas_devices', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=160),
               existing_nullable=False)
    connection = op.get_bind()
    duplicates = connection.execute(sa.text("""
        SELECT code FROM nas_devices
        WHERE code IS NOT NULL
        GROUP BY code
        HAVING COUNT(*) > 1
        LIMIT 1
    """)).fetchone()
    if duplicates:
        raise RuntimeError("Duplicate nas_devices.code values detected; resolve before migration.")
    nas_uniques = {tuple(u["column_names"]) for u in inspector.get_unique_constraints("nas_devices")}
    if ('code',) not in nas_uniques:
        op.create_unique_constraint(None, 'nas_devices', ['code'])
    nas_fks = {tuple(fk["constrained_columns"]) for fk in inspector.get_foreign_keys("nas_devices")}
    if ('pop_site_id',) not in nas_fks:
        op.create_foreign_key(None, 'nas_devices', 'pop_sites', ['pop_site_id'], ['id'])
    if ('network_device_id',) not in nas_fks:
        op.create_foreign_key(None, 'nas_devices', 'network_devices', ['network_device_id'], ['id'])

    radius_columns = {col["name"] for col in inspector.get_columns("radius_profiles")}
    def _add_radius_col(name, column):
        nonlocal radius_columns
        if name not in radius_columns:
            op.add_column('radius_profiles', column)
            radius_columns.add(name)

    _add_radius_col('code', sa.Column('code', sa.String(length=80), nullable=True))
    _add_radius_col('connection_type', sa.Column('connection_type', postgresql.ENUM('pppoe', 'dhcp', 'ipoe', 'static', 'hotspot', name='connectiontype', create_type=False), nullable=True))
    _add_radius_col('download_speed', sa.Column('download_speed', sa.Integer(), nullable=True))
    _add_radius_col('upload_speed', sa.Column('upload_speed', sa.Integer(), nullable=True))
    _add_radius_col('burst_download', sa.Column('burst_download', sa.Integer(), nullable=True))
    _add_radius_col('burst_upload', sa.Column('burst_upload', sa.Integer(), nullable=True))
    _add_radius_col('burst_threshold', sa.Column('burst_threshold', sa.Integer(), nullable=True))
    _add_radius_col('burst_time', sa.Column('burst_time', sa.Integer(), nullable=True))
    _add_radius_col('vlan_id', sa.Column('vlan_id', sa.Integer(), nullable=True))
    _add_radius_col('inner_vlan_id', sa.Column('inner_vlan_id', sa.Integer(), nullable=True))
    _add_radius_col('ip_pool_name', sa.Column('ip_pool_name', sa.String(length=120), nullable=True))
    _add_radius_col('ipv6_pool_name', sa.Column('ipv6_pool_name', sa.String(length=120), nullable=True))
    _add_radius_col('session_timeout', sa.Column('session_timeout', sa.Integer(), nullable=True))
    _add_radius_col('idle_timeout', sa.Column('idle_timeout', sa.Integer(), nullable=True))
    _add_radius_col('simultaneous_use', sa.Column('simultaneous_use', sa.Integer(), nullable=True))
    _add_radius_col('mikrotik_rate_limit', sa.Column('mikrotik_rate_limit', sa.String(length=255), nullable=True))
    _add_radius_col('mikrotik_address_list', sa.Column('mikrotik_address_list', sa.String(length=120), nullable=True))
    op.alter_column('radius_profiles', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=160),
               existing_nullable=False)
    duplicates = connection.execute(sa.text("""
        SELECT code FROM radius_profiles
        WHERE code IS NOT NULL
        GROUP BY code
        HAVING COUNT(*) > 1
        LIMIT 1
    """)).fetchone()
    if duplicates:
        raise RuntimeError("Duplicate radius_profiles.code values detected; resolve before migration.")
    radius_uniques = {tuple(u["column_names"]) for u in inspector.get_unique_constraints("radius_profiles")}
    if ('code',) not in radius_uniques:
        op.create_unique_constraint(None, 'radius_profiles', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'radius_profiles', type_='unique')
    op.alter_column('radius_profiles', 'name',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('radius_profiles', 'mikrotik_address_list')
    op.drop_column('radius_profiles', 'mikrotik_rate_limit')
    op.drop_column('radius_profiles', 'simultaneous_use')
    op.drop_column('radius_profiles', 'idle_timeout')
    op.drop_column('radius_profiles', 'session_timeout')
    op.drop_column('radius_profiles', 'ipv6_pool_name')
    op.drop_column('radius_profiles', 'ip_pool_name')
    op.drop_column('radius_profiles', 'inner_vlan_id')
    op.drop_column('radius_profiles', 'vlan_id')
    op.drop_column('radius_profiles', 'burst_time')
    op.drop_column('radius_profiles', 'burst_threshold')
    op.drop_column('radius_profiles', 'burst_upload')
    op.drop_column('radius_profiles', 'burst_download')
    op.drop_column('radius_profiles', 'upload_speed')
    op.drop_column('radius_profiles', 'download_speed')
    op.drop_column('radius_profiles', 'connection_type')
    op.drop_column('radius_profiles', 'code')
    op.drop_constraint(None, 'nas_devices', type_='foreignkey')
    op.drop_constraint(None, 'nas_devices', type_='foreignkey')
    op.drop_constraint(None, 'nas_devices', type_='unique')
    op.alter_column('nas_devices', 'name',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('nas_devices', 'network_device_id')
    op.drop_column('nas_devices', 'tags')
    op.drop_column('nas_devices', 'notes')
    op.drop_column('nas_devices', 'last_seen_at')
    op.drop_column('nas_devices', 'status')
    op.drop_column('nas_devices', 'last_backup_at')
    op.drop_column('nas_devices', 'backup_schedule')
    op.drop_column('nas_devices', 'backup_method')
    op.drop_column('nas_devices', 'backup_enabled')
    op.drop_column('nas_devices', 'default_connection_type')
    op.drop_column('nas_devices', 'supported_connection_types')
    op.drop_column('nas_devices', 'snmp_port')
    op.drop_column('nas_devices', 'snmp_version')
    op.drop_column('nas_devices', 'snmp_community')
    op.drop_column('nas_devices', 'api_url')
    op.drop_column('nas_devices', 'api_token')
    op.drop_column('nas_devices', 'api_password')
    op.drop_column('nas_devices', 'api_username')
    op.drop_column('nas_devices', 'ssh_key')
    op.drop_column('nas_devices', 'ssh_password')
    op.drop_column('nas_devices', 'ssh_username')
    op.drop_column('nas_devices', 'coa_port')
    op.drop_column('nas_devices', 'nas_ip')
    op.drop_column('nas_devices', 'management_port')
    op.drop_column('nas_devices', 'management_ip')
    op.drop_column('nas_devices', 'rack_position')
    op.drop_column('nas_devices', 'pop_site_id')
    op.drop_column('nas_devices', 'firmware_version')
    op.drop_column('nas_devices', 'serial_number')
    op.drop_column('nas_devices', 'model')
    op.drop_column('nas_devices', 'code')
    op.drop_table('provisioning_logs')
    op.drop_table('nas_config_backups')
    op.drop_table('provisioning_templates')
    op.execute("DROP TYPE IF EXISTS nasdevicestatus")
    op.execute("DROP TYPE IF EXISTS configbackupmethod")
    op.execute("DROP TYPE IF EXISTS provisioningaction")
    op.execute("DROP TYPE IF EXISTS connectiontype")
    # ### end Alembic commands ###
