"""Provider-neutral capability IDs for back-office collaboration."""

ERP_OUTBOX_CAPABILITY = "erp.outbox.deliver.v1"
ERP_STATUS_CAPABILITY = "erp.status.read.v1"
ERP_INVENTORY_CAPABILITY = "erp.inventory.read.v1"
ERP_MATERIAL_STATUS_WEBHOOK_CAPABILITY = "erp.material_status.webhook.v1"
ERP_OPERATIONAL_SYNC_CAPABILITY = "erp.operational_context.sync.v1"
ERP_REGULATORY_CAPABILITY = "erp.regulatory.read.v1"
WORKFORCE_ATTENDANCE_READ_CAPABILITY = "workforce.attendance.read.v1"
WORKFORCE_ATTENDANCE_PUNCH_CAPABILITY = "workforce.attendance.punch.v1"
