#!/usr/bin/env bash
# Deploy the Sub Thin Shadow stack onto a host that already runs something else.
#
# The target host (idp) runs live Keycloak. Everything defensive in this script
# follows from that single fact: the shadow stack is a guest, and a guest that
# disturbs its host has failed no matter how well its own containers came up.
#
# So Keycloak's identity is captured BEFORE anything is created and compared
# AFTER. On any difference the script removes only the shadow application
# container and fails. It never touches Keycloak, never removes shadow volumes
# (destruction is a separately authorized act), and never prints a secret.
set -euo pipefail

# Everything by config, with a documented default.
: "${SHADOW_DIR:=/opt/dotmac-sub-thin-shadow}"
: "${SHADOW_PROJECT:=dotmac-sub-thin-shadow}"
: "${SHADOW_COMPOSE:=${SHADOW_DIR}/docker-compose.shadow.yml}"
: "${SHADOW_ENV:=${SHADOW_DIR}/.env}"
: "${SHADOW_EVIDENCE:=${SHADOW_DIR}/evidence}"
: "${SHADOW_APP_CONTAINER:=dotmac_sub_thin_shadow_app}"
: "${SHADOW_BIND:=127.0.0.1:18001}"
: "${KEYCLOAK_PROJECT:=keycloak}"
: "${HEALTH_TIMEOUT_SECONDS:=180}"

: "${APP_DIGEST:=sha256:342a9b805d6ac9d56a116b9ac833c594b0ccd5f2f79a9b6c75b3f85ba36885d4}"
: "${POSTGIS_DIGEST:=sha256:681931a625df344215e9b8998bf34daf146b6a395ceacee4439eb9c85869239f}"
: "${REDIS_DIGEST:=sha256:e7723ff73d963f5cc6d9c4643ea3d989527a402a319239054e9472a7fb9219a2}"

log() { printf '[shadow] %s\n' "$*" >&2; }
die() { printf '[shadow][FATAL] %s\n' "$*" >&2; exit 1; }

compose() { docker compose -p "${SHADOW_PROJECT}" -f "${SHADOW_COMPOSE}" "$@"; }

# ── Keycloak identity ───────────────────────────────────────────────────────
# Image, created time and health as well as the container ID: a recreate that
# happened to reuse an ID would still be a disturbance, and a container that is
# up but unhealthy is a disturbance the ID alone cannot show.
keycloak_identity() {
  docker ps -a \
    --filter "label=com.docker.compose.project=${KEYCLOAK_PROJECT}" \
    --format '{{.ID}} {{.Names}} {{.Image}} {{.CreatedAt}} {{.Status}}' \
    | sort
}

# ── Preflight ───────────────────────────────────────────────────────────────
[ -f "${SHADOW_COMPOSE}" ] || die "compose file not found: ${SHADOW_COMPOSE}"
mkdir -p "${SHADOW_EVIDENCE}"

log "verifying pinned images are present locally (no pull: the digest is the review)"
for digest in "${APP_DIGEST}" "${POSTGIS_DIGEST}" "${REDIS_DIGEST}"; do
  docker image inspect "${digest}" >/dev/null 2>&1 \
    || die "pinned image ${digest} is not present on this host"
done

# ── Credentials: generated here, never printed, never committed ─────────────
if [ ! -f "${SHADOW_ENV}" ]; then
  log "generating shadow credentials into ${SHADOW_ENV} (mode 0600)"
  command -v openssl >/dev/null 2>&1 || die "openssl is required to generate credentials"
  (
    umask 077
    {
      echo "# Generated by deploy-shadow.sh. Mode 0600, untracked, host-only."
      echo "# Synthetic environment credentials: they protect disposable data."
      echo "SHADOW_DB_NAME=dotmac_sub_shadow"
      echo "SHADOW_DB_USER=shadow_app"
      echo "SHADOW_DB_PASSWORD=$(openssl rand -hex 32)"
      echo "SHADOW_REDIS_PASSWORD=$(openssl rand -hex 32)"
    } > "${SHADOW_ENV}"
  )
fi
chmod 0600 "${SHADOW_ENV}"
[ "$(stat -c '%a' "${SHADOW_ENV}")" = "600" ] || die "${SHADOW_ENV} is not mode 0600"

# ── Before ──────────────────────────────────────────────────────────────────
before="${SHADOW_EVIDENCE}/keycloak-before.txt"
keycloak_identity > "${before}"
[ -s "${before}" ] || die "no Keycloak containers found; refusing to deploy onto an unexpected host"
log "captured Keycloak baseline ($(wc -l < "${before}") containers)"

# ── Up ──────────────────────────────────────────────────────────────────────
log "starting shadow stack (project ${SHADOW_PROJECT})"
compose up -d --no-build

# ── Health ──────────────────────────────────────────────────────────────────
log "waiting for shadow app health on ${SHADOW_BIND} (timeout ${HEALTH_TIMEOUT_SECONDS}s)"
deadline=$(( $(date +%s) + HEALTH_TIMEOUT_SECONDS ))
healthy=0
while [ "$(date +%s)" -lt "${deadline}" ]; do
  if curl -fsS -m 5 "http://${SHADOW_BIND}/health" >/dev/null 2>&1; then
    healthy=1
    break
  fi
  sleep 5
done

# ── After: the host must be untouched ───────────────────────────────────────
after="${SHADOW_EVIDENCE}/keycloak-after.txt"
keycloak_identity > "${after}"
if ! diff -u "${before}" "${after}" > "${SHADOW_EVIDENCE}/keycloak-diff.txt"; then
  log "KEYCLOAK CHANGED — removing only the shadow application container"
  docker rm -f "${SHADOW_APP_CONTAINER}" >/dev/null 2>&1 || true
  cat "${SHADOW_EVIDENCE}/keycloak-diff.txt" >&2
  die "Keycloak identity or health changed during deployment"
fi
log "Keycloak identity and health unchanged"

[ "${healthy}" = "1" ] || {
  log "shadow app did not become healthy; leaving containers for diagnosis"
  die "health check failed on http://${SHADOW_BIND}/health"
}
log "shadow app healthy on http://${SHADOW_BIND}/health"

# ── Egress must be refused ──────────────────────────────────────────────────
# Proven from inside the container rather than asserted from the compose file:
# `internal: true` is the mechanism, this is the evidence.
log "probing egress refusal from inside the shadow app container"
if docker exec "${SHADOW_APP_CONTAINER}" \
     python -c "import socket,sys; socket.setdefaulttimeout(5); \
sys.exit(0 if __import__('socket').create_connection(('1.1.1.1',443)) else 0)" \
     >/dev/null 2>&1; then
  docker rm -f "${SHADOW_APP_CONTAINER}" >/dev/null 2>&1 || true
  die "shadow container reached the internet — egress is NOT denied"
fi
log "egress refused as expected"

log "deployment complete. Volumes are preserved by design; destruction is a separate act."
