#!/usr/bin/env python3
"""Render the derived module schema contract into one checked-in document.

There used to be three hand-maintained prose lists of the ``mod_*`` schemas —
in ADR-0011's amendment, in the production runbook, and in the platform
adoption ledger. Two were stale and one was wrong, which is a fair description
of what hand-maintained parallel lists always become. This renders the single
derived answer instead; the documents link to it rather than restating it.

``--check`` is a byte comparison, wired into ``make check``.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from app.commercial_module_prereqs import (  # noqa: E402
    PUBLIC_PROBE_ROLE,
    SCHEMA_BOOTSTRAP_ROLE,
    module_schema_contract,
)

TARGET = REPO_ROOT / "docs" / "generated" / "MODULE_SCHEMA_CONTRACT.md"


def render() -> str:
    contract = module_schema_contract()
    owners = sorted({item.owner_role for item in contract})
    usage = sorted({role for item in contract for role in item.usage_roles})

    lines = [
        "<!-- GENERATED by scripts/render_module_schema_contract.py - do not edit. -->",
        "",
        "# Module database schema contract",
        "",
        "Derived, not maintained. Every composed lineage in `alembic.ini` names an",
        "installed distribution; that distribution declares its own `short_code` on",
        "its `ModuleManifest`; and `dotmac_kernel.namespaces.module_schema` turns a",
        "short code into the one immutable `mod_*` name. Adding a module to",
        "`alembic.ini` therefore adds it here, and to the bootstrap and the",
        "verifier, in the same act.",
        "",
        "Regenerate with `make schema-contract`; `make schema-contract-check` fails",
        "the build on drift.",
        "",
        "## Schemas",
        "",
        "| schema | module | distribution | import name | owner |",
        "| --- | --- | --- | --- | --- |",
    ]
    for item in contract:
        lines.append(
            f"| `{item.schema}` | {item.module} | `{item.distribution}` | "
            f"`{item.import_name}` | `{item.owner_role}` |"
        )
    lines += [
        "",
        "## Contract for every schema above",
        "",
        f"- Owner: {', '.join(f'`{role}`' for role in owners)}.",
        f"- `USAGE` granted to: {', '.join(f'`{role}`' for role in usage)}.",
        "- No privileges for `PUBLIC`. This is asserted as denial, not as an",
        f"  absent grant row: the no-privilege probe role `{PUBLIC_PROBE_ROLE}`",
        "  must hold neither `USAGE` nor `CREATE`, checked with",
        "  `has_schema_privilege`, which is transitive through role membership.",
        "",
        "## Who creates them",
        "",
        f"`scripts/bootstrap_commercial_module_prereqs.py`, holding `{SCHEMA_BOOTSTRAP_ROLE}`",
        "for the managed deployment leg or a superuser connection for one-off",
        "provisioning. Never Alembic: the restricted migration role deliberately",
        "does not hold database-level `CREATE` (ADR-0011). A module lineage's own",
        "`CREATE SCHEMA` is intercepted by `app/migration_schema_ops.py`.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rendered = render()
    if not args.check:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(rendered, encoding="utf-8")
        print(f"wrote {TARGET.relative_to(REPO_ROOT)}")
        return 0

    if not TARGET.exists():
        print(
            f"{TARGET.relative_to(REPO_ROOT)} is missing; run `make schema-contract`.",
            file=sys.stderr,
        )
        return 1
    if TARGET.read_text(encoding="utf-8") != rendered:
        print(
            f"{TARGET.relative_to(REPO_ROOT)} is stale; run `make schema-contract`.",
            file=sys.stderr,
        )
        return 1
    print(f"{TARGET.relative_to(REPO_ROOT)} matches the derived contract")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
