#!/usr/bin/env python3
"""Void prepaid "phantom" invoices generated by the faulty postpaid runner.

Background
----------
Until #301, ``run_invoice_cycle`` had no ``billing_mode`` filter and generated
postpaid-style, balance-due invoices for PREPAID accounts before the monthly
prepaid invoicing cutover. The generation bug is fixed, but the bad invoice rows
still exist and inflate ledger balances / AR. This one-off voids them.

It targets ONLY runner-generated prepaid phantoms — and reuses the canonical
``Invoices.void`` so each void posts structurally linked, append-only reversing
credit entries while the original debits remain active. Historical prepaid debit ledger entries
(``invoice_id IS NULL``, memo "Prepaid charge ...") are NOT touched by void.

Targeting (a candidate must match ALL):
  * the invoice's account (Subscriber) is ``billing_mode == prepaid``
  * ``splynx_invoice_id IS NULL``    (locally generated, not migrated)
  * ``added_by_id IS NULL``          (automated runner, not an admin/credit invoice)
  * ``billing_period_start IS NOT NULL`` (a billing-cycle invoice)
  * ``invoice_number IS NOT NULL``   (real INV- number)
  * status is not already ``void``; ``is_active``
  * no credit-exception marker in ``metadata`` (``credit_exception`` / ``void_reason``)

Classification:
  * paid / partially_paid  -> MANUAL REVIEW only (never auto-mutated; voiding a
    paid invoice would strand the payment)
  * unpaid (draft/issued/overdue) on an account that ALSO has a historical
    prepaid debit entry -> LEGACY-DEBIT-OVERLAP: void invoice, debit preserved
  * unpaid, no legacy debit overlap -> VOID candidate

Safe by default: prints a summary and writes CSV artifacts for every class.
Pass ``--apply`` to void the two unpaid classes. Never deletes rows.

Usage (inside the app container)::

    python scripts/one_off/cleanup_prepaid_phantom_invoices.py            # dry-run
    python scripts/one_off/cleanup_prepaid_phantom_invoices.py --apply
    python scripts/one_off/cleanup_prepaid_phantom_invoices.py --out /tmp
"""

from __future__ import annotations

import argparse
import csv
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from app.db import SessionLocal  # noqa: E402
from app.models.billing import Invoice, InvoiceStatus, LedgerEntry  # noqa: E402
from app.models.catalog import BillingMode  # noqa: E402
from app.models.subscriber import Subscriber  # noqa: E402
from app.services.billing.invoices import Invoices  # noqa: E402

VOID_REASON = "prepaid_phantom_invoice_cleanup"
PREPAID_CHARGE_MEMO_PREFIX = "Prepaid charge"

# Unpaid statuses we will auto-void; everything else (paid/partially_paid) is
# manual review only.
VOIDABLE = {
    InvoiceStatus.draft,
    InvoiceStatus.issued,
    InvoiceStatus.overdue,
}


def _has_credit_marker(inv: Invoice) -> bool:
    meta = inv.metadata_ or {}
    return bool(meta.get("credit_exception")) or bool(meta.get("void_reason"))


def candidates(db) -> list[Invoice]:
    """Runner-generated prepaid phantom invoices (excludes admin/credit/migrated)."""
    rows = (
        db.query(Invoice)
        .join(Subscriber, Subscriber.id == Invoice.account_id)
        .filter(Subscriber.billing_mode == BillingMode.prepaid)
        .filter(Invoice.splynx_invoice_id.is_(None))
        .filter(Invoice.added_by_id.is_(None))
        .filter(Invoice.billing_period_start.isnot(None))
        .filter(Invoice.invoice_number.isnot(None))
        .filter(Invoice.status != InvoiceStatus.void)
        .filter(Invoice.is_active.is_(True))
        .all()
    )
    return [inv for inv in rows if not _has_credit_marker(inv)]


def _legacy_prepaid_debit_accounts(db, account_ids) -> set:
    """Accounts that have a historical prepaid debit ledger entry."""
    if not account_ids:
        return set()
    rows = (
        db.query(LedgerEntry.account_id)
        .filter(LedgerEntry.account_id.in_(list(account_ids)))
        .filter(LedgerEntry.memo.like(f"{PREPAID_CHARGE_MEMO_PREFIX}%"))
        .filter(LedgerEntry.is_active.is_(True))
        .distinct()
        .all()
    )
    return {r[0] for r in rows}


def classify(db) -> dict[str, list[Invoice]]:
    invs = candidates(db)
    overlap = _legacy_prepaid_debit_accounts(db, {i.account_id for i in invs})
    out: dict[str, list[Invoice]] = {
        "void_candidate": [],
        "legacy_debit_overlap": [],
        "manual_review": [],
    }
    for inv in invs:
        if inv.status not in VOIDABLE:
            out["manual_review"].append(inv)
        elif inv.account_id in overlap:
            out["legacy_debit_overlap"].append(inv)
        else:
            out["void_candidate"].append(inv)
    return out


def _row(inv: Invoice) -> dict:
    return {
        "invoice_id": str(inv.id),
        "invoice_number": inv.invoice_number,
        "account_id": str(inv.account_id),
        "status": getattr(inv.status, "value", inv.status),
        "total": f"{inv.total:.2f}" if inv.total is not None else "",
        "balance_due": f"{inv.balance_due:.2f}" if inv.balance_due is not None else "",
        "billing_period_start": inv.billing_period_start,
        "billing_period_end": inv.billing_period_end,
        "created_at": inv.created_at,
    }


def _write_csv(path: Path, rows: list[dict]) -> None:
    cols = [
        "invoice_id",
        "invoice_number",
        "account_id",
        "status",
        "total",
        "balance_due",
        "billing_period_start",
        "billing_period_end",
        "created_at",
    ]
    with path.open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        for r in rows:
            w.writerow(r)


def void_invoice(db, inv: Invoice, now: datetime) -> None:
    """Stamp audit metadata, then void via the canonical service (commits)."""
    inv.metadata_ = {
        **(inv.metadata_ or {}),
        "void_reason": VOID_REASON,
        "original_status": getattr(inv.status, "value", str(inv.status)),
        "original_total": str(inv.total),
        "original_balance_due": str(inv.balance_due),
        "voided_at": now.isoformat(),
    }
    db.add(inv)
    Invoices.void(db, str(inv.id), memo=VOID_REASON)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--apply",
        action="store_true",
        help="void the two unpaid classes (default: dry-run)",
    )
    ap.add_argument("--out", default=".", help="directory for CSV artifacts")
    args = ap.parse_args()
    out = Path(args.out)
    now = datetime.now(UTC)

    db = SessionLocal()
    try:
        groups = classify(db)
        for name, rows in groups.items():
            _write_csv(out / f"prepaid_phantom_{name}.csv", [_row(i) for i in rows])
            total = sum((i.balance_due or 0) for i in rows)
            print(
                f"{name:18}: {len(rows):5} invoice(s), ₦{total:,.2f} balance_due "
                f"-> {out}/prepaid_phantom_{name}.csv"
            )

        to_void = groups["void_candidate"] + groups["legacy_debit_overlap"]
        print(
            f"\nmanual_review ({len(groups['manual_review'])}): NOT mutated — paid/partial/completed, review by hand."
        )

        if not args.apply:
            print(
                f"\nDRY-RUN: {len(to_void)} invoice(s) would be voided. Re-run with --apply."
            )
            return

        voided = 0
        for inv in to_void:
            try:
                void_invoice(db, inv, now)
                voided += 1
            except Exception as exc:  # noqa: BLE001
                print(f"  ERROR voiding {inv.invoice_number}: {exc!r}")
        print(
            f"\nAPPLIED: voided {voided}/{len(to_void)} invoice(s) "
            f"(reversing ledger credits posted; historical prepaid debits preserved)."
        )
    finally:
        db.close()


if __name__ == "__main__":
    main()
