from __future__ import annotations

from typing import Any


class AutoAddPolicy: ...


class RejectPolicy: ...


class RSAKey:
    @classmethod
    def from_private_key(cls, file_obj: Any) -> Any: ...
    @classmethod
    def from_private_key_file(cls, filename: str, password: str | None = ...) -> Any: ...


class SSHClient:
    def __init__(self) -> None: ...
    def set_missing_host_key_policy(self, policy: Any) -> None: ...
    def load_system_host_keys(self) -> None: ...
    def connect(
        self,
        hostname: str,
        port: int = ...,
        username: str | None = ...,
        password: str | None = ...,
        pkey: Any = ...,
        timeout: float | int | None = ...,
    ) -> None: ...
    def exec_command(
        self, command: str, timeout: float | int | None = ...
    ) -> tuple[Any, Any, Any]: ...
    def close(self) -> None: ...
