"""Assemble the canonical provisioning_operations SOT domain from capability shards."""

from __future__ import annotations

from app.services.automation_contracts import (
    AutomationActionCapability,
    AutomationActionInput,
    AutomationCatalogItem,
    AutomationCatalogState,
    AutomationDomainCapabilities,
    AutomationScriptTargetCapability,
    AutomationTriggerCapability,
    AutomationValueType,
)
from app.services.sot_registry.domains.provisioning_operations.core import (
    SERVICES as CORE_SERVICES,
)
from app.services.sot_registry.domains.provisioning_operations.vendor_delivery import (
    SERVICES as VENDOR_DELIVERY_SERVICES,
)
from app.services.sot_registry.domains.provisioning_operations.vendor_identity import (
    SERVICES as VENDOR_IDENTITY_SERVICES,
)
from app.services.sot_registry.model import DomainSOT

DOMAIN = DomainSOT(
    domain="provisioning_operations",
    setting_domains=(
        "provisioning",
        "projects",
        "inventory",
        "field",
    ),
    services=(
        *CORE_SERVICES,
        *VENDOR_IDENTITY_SERVICES,
        *VENDOR_DELIVERY_SERVICES,
    ),
    entrypoints=(
        "app.services.events.handlers.provisioning",
        "app.tasks.ont_provisioning",
        "app.web.admin.provisioning",
        "app.web.admin.projects",
        "app.web.vendor_portal",
        "app.api.vendor_portal",
        "app.api.projects",
        "app.api.field.*",
        "app.services.web_projects",
        "app.services.web_dispatch_work_orders",
        "app.services.work_order_commands",
        "field_mobile",
    ),
    rule="Provisioning callers resolve customer/network context through the "
    "shared context layer before executing workflow steps. Native project "
    "mutation adapters delegate to Projects.update for lifecycle consequences. "
    "Field clients consume completion_requirements from authenticated job "
    "detail and leave completion eligibility to the field transition service. "
    "Dispatch adapters delegate native work-order and assignment writes to "
    "operations.work_order_commands.",
    automation=AutomationDomainCapabilities(
        target_types=(
            "operations.project",
            "operations.work_order",
            "operations.material_request",
            "operations.vendor",
        ),
        triggers=(
            AutomationTriggerCapability(
                key="operations.project.created",
                label="Project created",
                event_type="project.created",
                event_schema_version=1,
                entity_type="operations.project",
                tenant_id_field="tenant_id",
                entity_id_field="project_id",
                fields=(),
                author_permission="operations:project:read",
                runtime_enabled=True,
            ),
            AutomationTriggerCapability(
                key="operations.work_order.created",
                label="Work order created",
                event_type="work_order.created",
                event_schema_version=1,
                entity_type="operations.work_order",
                tenant_id_field="tenant_id",
                entity_id_field="work_order_id",
                fields=(),
                author_permission="operations:dispatch:read",
                runtime_enabled=True,
            ),
            AutomationTriggerCapability(
                key="operations.material_request.cancellation_requested",
                label="Material request cancellation requested",
                event_type="field_material_request.cancellation_requested",
                event_schema_version=1,
                entity_type="operations.material_request",
                tenant_id_field="tenant_id",
                entity_id_field="material_request_id",
                fields=(),
                author_permission="operations:material_request:read",
                runtime_enabled=True,
            ),
            AutomationTriggerCapability(
                key="operations.vendor.project_completed",
                label="Vendor project completed",
                event_type="vendor_project.completed",
                event_schema_version=1,
                entity_type="operations.vendor",
                tenant_id_field="tenant_id",
                entity_id_field="project_id",
                fields=(),
                author_permission="vendor:read",
                runtime_enabled=True,
            ),
        ),
        actions=(
            AutomationActionCapability(
                key="operations.project.set_status",
                label="Set project status",
                entity_type="operations.project",
                command_owner="operations.project_lifecycle",
                command_name="update_status",
                input_schema_version=1,
                inputs=(
                    AutomationActionInput(
                        key="status",
                        label="Status",
                        value_type=AutomationValueType.enum,
                        enum_values=(
                            "open",
                            "planned",
                            "active",
                            "on_hold",
                            "completed",
                            "canceled",
                        ),
                    ),
                ),
                author_permission="operations:project:write",
                runtime_scope="one project",
                idempotency="tenant/project/status/version",
                runtime_enabled=True,
            ),
            AutomationActionCapability(
                key="operations.work_order.set_status",
                label="Set work-order status",
                entity_type="operations.work_order",
                command_owner="operations.work_order_commands",
                command_name="update_status",
                input_schema_version=1,
                inputs=(
                    AutomationActionInput(
                        key="status",
                        label="Status",
                        value_type=AutomationValueType.enum,
                        enum_values=(
                            "draft",
                            "scheduled",
                        ),
                    ),
                ),
                author_permission="operations:dispatch:write",
                runtime_scope="one work order",
                idempotency="tenant/work-order/status/version",
                runtime_enabled=True,
            ),
            AutomationActionCapability(
                key="operations.material_request.enqueue_cancellation",
                label="Queue material-request cancellation",
                entity_type="operations.material_request",
                command_owner="operations.material_dependencies",
                command_name="consume_material_request_cancellation_requested",
                input_schema_version=1,
                inputs=(),
                author_permission="operations:material_request:write",
                runtime_scope="one material request",
                idempotency="tenant/material-request/cancellation-event",
                runtime_enabled=True,
            ),
            AutomationActionCapability(
                key="operations.vendor.set_status",
                label="Set vendor-project status",
                entity_type="operations.vendor",
                command_owner="operations.vendor_project_automation",
                command_name="transition_status",
                input_schema_version=1,
                inputs=(
                    AutomationActionInput(
                        key="status",
                        label="Status",
                        value_type=AutomationValueType.enum,
                        enum_values=("in_progress", "completed"),
                    ),
                ),
                author_permission="vendor:write",
                runtime_scope="one vendor project",
                idempotency="tenant/vendor-project/status/version",
                runtime_enabled=True,
            ),
        ),
        script_targets=(
            AutomationScriptTargetCapability(
                key="operations.project",
                label="Project",
                entity_type="operations.project",
                client_events=("form.load", "field.change", "form.validate"),
                server_events=(
                    "project.created",
                    "project.updated",
                    "project.completed",
                    "project.canceled",
                ),
                read_permission="operations:project:read",
                write_permission="operations:project:write",
                tenant_id_field="tenant_id",
                entity_id_field="project_id",
            ),
            AutomationScriptTargetCapability(
                key="operations.work_order",
                label="Work order",
                entity_type="operations.work_order",
                client_events=("form.load", "field.change", "form.validate"),
                server_events=("work_order.created", "work_order.updated"),
                read_permission="operations:dispatch:read",
                write_permission="operations:dispatch:write",
                tenant_id_field="tenant_id",
                entity_id_field="work_order_id",
            ),
            AutomationScriptTargetCapability(
                key="operations.material_request",
                label="Material request",
                entity_type="operations.material_request",
                client_events=("form.load", "field.change", "form.validate"),
                server_events=(
                    "field_material_request.approved",
                    "field_material_request.cancellation_requested",
                    "field_material_request.fulfilled",
                ),
                read_permission="operations:material_request:read",
                write_permission="operations:material_request:write",
                tenant_id_field="tenant_id",
                entity_id_field="material_request_id",
            ),
            AutomationScriptTargetCapability(
                key="operations.vendor",
                label="Vendor project",
                entity_type="operations.vendor",
                client_events=("form.load", "field.change", "form.validate"),
                server_events=(
                    "vendor_project.published",
                    "vendor_project.completed",
                    "vendor_project.verified",
                ),
                read_permission="vendor:read",
                write_permission="vendor:write",
                tenant_id_field="tenant_id",
                entity_id_field="project_id",
            ),
        ),
        catalog_items=(
            AutomationCatalogItem(
                key="provisioning.subscription_activation",
                label="Subscription activation provisioning",
                group="Provisioning",
                state=AutomationCatalogState.unavailable,
                explanation="Activation provisions network access through linked lifecycle owners; the ordered steps are not yet registered as Center actions.",
            ),
            AutomationCatalogItem(
                key="provisioning.subscription_resume",
                label="Subscription-resume provisioning",
                group="Provisioning",
                state=AutomationCatalogState.unavailable,
                explanation="Resume and access restoration remain in the existing provisioning flow; no Center trigger or safe action is registered.",
            ),
            AutomationCatalogItem(
                key="provisioning.service_order_workflow",
                label="Service-order provisioning workflow",
                group="Provisioning",
                state=AutomationCatalogState.unavailable,
                explanation="The service-order workflow includes dependent provisioning steps owned by current services and is not yet available as Center actions.",
            ),
            AutomationCatalogItem(
                key="provisioning.readiness_decision",
                label="Provisioning readiness decision",
                group="Provisioning",
                state=AutomationCatalogState.unavailable,
                explanation="Readiness checks stay in the provisioning owner; a rule cannot bypass their required checks.",
            ),
            AutomationCatalogItem(
                key="provisioning.stale_run_cleanup",
                label="Stale provisioning-run cleanup",
                group="Provisioning",
                state=AutomationCatalogState.unavailable,
                explanation="Cleanup is a protected recovery job and is not an editable customer-business action in the Center.",
            ),
            AutomationCatalogItem(
                key="provisioning.compensation_retry",
                label="Provisioning compensation retry",
                group="Provisioning",
                state=AutomationCatalogState.unavailable,
                explanation="Retrying compensation can affect service access and remains under its existing recovery safeguards.",
            ),
            AutomationCatalogItem(
                key="provisioning.bulk_activation_migration",
                label="Background bulk activation and migration",
                group="Provisioning",
                state=AutomationCatalogState.unavailable,
                explanation="Bulk activation is an operator-started process with bounded migration safeguards, not a reusable per-customer rule action.",
            ),
            AutomationCatalogItem(
                key="field.approved_material_request_export",
                label="Approved material request export",
                group="Field operations and ERP",
                state=AutomationCatalogState.unavailable,
                explanation="ERP delivery follows the approved field-request owner and integration outbox; a Center action is not registered.",
            ),
            AutomationCatalogItem(
                key="field.material_request_cancellation_export",
                label="Material-request cancellation export",
                group="Field operations and ERP",
                state=AutomationCatalogState.unavailable,
                explanation="Cancellation delivery is governed by the field request and ERP integration owners; no Center action is registered.",
            ),
        ),
    ),
)
