"""add document_sequences table

Revision ID: 2eef37e08a0f
Revises: 6ebaf94af561
Create Date: 2026-01-10 16:15:37.088355

"""

from alembic import op
import sqlalchemy as sa


revision = '2eef37e08a0f'
down_revision = '6ebaf94af561'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_document_sequences_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_sequences')
    # ### end Alembic commands ###
