"""add_fiber_access_points_and_service_buildings

Revision ID: dd4f107ba42b
Revises: 75dc9b60dbcc
Create Date: 2026-01-14 13:03:46.855484

"""

from alembic import op
import geoalchemy2
import sqlalchemy as sa

revision = 'dd4f107ba42b'
down_revision = '75dc9b60dbcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'fiber_access_points' not in existing_tables:
        op.create_table('fiber_access_points',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('code', sa.String(length=60), nullable=True),
        sa.Column('name', sa.String(length=160), nullable=False),
        sa.Column('access_point_type', sa.String(length=60), nullable=True),
        sa.Column('placement', sa.String(length=60), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
        sa.Column('street', sa.String(length=200), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('county', sa.String(length=100), nullable=True),
        sa.Column('state', sa.String(length=60), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
        )
    op.create_index('idx_fiber_access_points_geom', 'fiber_access_points', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)

    if 'service_buildings' not in existing_tables:
        op.create_table('service_buildings',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('code', sa.String(length=60), nullable=True),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('clli', sa.String(length=20), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
        sa.Column('boundary_geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
        sa.Column('street', sa.String(length=200), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('state', sa.String(length=60), nullable=True),
        sa.Column('zip_code', sa.String(length=20), nullable=True),
        sa.Column('work_order', sa.String(length=100), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
        )
    op.create_index('idx_service_buildings_boundary_geom', 'service_buildings', ['boundary_geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index('idx_service_buildings_geom', 'service_buildings', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_service_buildings_geom', table_name='service_buildings', postgresql_using='gist')
    op.drop_index('idx_service_buildings_boundary_geom', table_name='service_buildings', postgresql_using='gist')
    op.drop_table('service_buildings')
    op.drop_index('idx_fiber_access_points_geom', table_name='fiber_access_points', postgresql_using='gist')
    op.drop_table('fiber_access_points')
    # ### end Alembic commands ###
